### ISSUE TITLE
hex package?

### ISSUE THREAD

**Issue by veverkap** [fmcgeough/ex_aws_elastic_load_balancing#10]
Are you planning on publishing this library to hex or will it always be a github install?

**Comment by fmcgeough** [comment]
@veverkap Yeah. I should do that. I've been a bit overwhelmed with work and haven't done it yet. Thanks for the reminder!

**Comment by fmcgeough** [comment]
@veverkap published it just now. Thanks for the friendly prodding to get this done! I'll work on the other ones we've developed.
