### ISSUE TITLE
Target group type a bit confusing. 

### ISSUE THREAD

**Issue by cdegroot** [fmcgeough/ex_aws_elastic_load_balancing#15]
The type definition for `target_description`:

```elixir
 @type target_description :: [
          id: binary,
          port: integer,
          availability_zone: binary
        ]
```

only allows a keyword list, and with Dialyzer involved this means writing something like `[[id: "foo"]]` to satisfy the type. However, the actual allowed data is a keyword list or a map (and I guess maybe other things) and the examples use either maps or a naked ID (I'm not sure that the latter will work with the API though) for register/deregister. 

Reason I'm submitting in issue first and not a PR right away is that I'm not sure whether the typespec should be changed/widened up or whether the examples should be adapted - more than happy to do either after a decision :)

(Hi, Frank!)

**Comment by fmcgeough** [comment]
Hey! I apologize but I'm just getting back to these libraries to give them some time and correct some things. I think you're right. I think this should be changed to: 

```
  @type target_description :: %{required(:id) => binary, optional(:port) => integer, optional(:availability_zone) => binary}
  @type target_descriptions :: [target_description()]
```

In the Go code its: 

```
    "TargetDescription":{
      "type":"structure",
      "required":["Id"],
      "members":{
        "Id":{"shape":"TargetId"},
        "Port":{"shape":"Port"},
        "AvailabilityZone":{"shape":"ZoneName"}
      }
    },
    "TargetDescriptions":{
      "type":"list",
      "member":{"shape":"TargetDescription"}
    },
```
https://github.com/aws/aws-sdk-go/blob/main/models/apis/elasticloadbalancingv2/2015-12-01/api-2.json

See https://github.com/fmcgeough/ex_aws_elastic_load_balancing/pull/17
