### ISSUE TITLE
describe_load_balancers() does not include ELB Classic load balancers

### ISSUE THREAD

**Issue by fastjames** [fmcgeough/ex_aws_elastic_load_balancing#2]
I didn't see this mentioned elsewhere, so I wanted to confirm my hypothesis. I currently have 3 entries on the Load Balancers section of my AWS admin: 2 are classics and one is an ALB. When I call `describe_load_balancers()` I only receive information on the ALB. I found a note in some AWS documentation indicating that the old and new ELB types might be accessible via different API versions. Is this expected behavior?

**Comment by fastjames** [comment]
Reinforcing my guess, if I modify the API version in my request I appear to get the ELB Classic load balancers in the response XML.

**Comment by fmcgeough** [comment]
@fastjames yep. There is both an old and a new API for load balancers. The old one has to be used for classic balancers - ExAws.ElasticLoadBalancing. The app / network balancers are obtained via the ExAws.ElasticLoadBalancingV2
